import "server-only";

import { AGENTS_BY_ID } from "@/lib/company/agents";
import { DEPARTMENTS } from "@/lib/company/departments";
import { PROJECTS_BY_ID } from "@/lib/company/projects";
import { formatDate } from "@/lib/time";
import {
  REPORT_TYPE_LABEL,
  type DepartmentId,
  type Priority,
  type Report,
  type ReportContent,
  type ReportType,
} from "@/lib/types";
import { mutate, read } from "@/server/runtime/store";
import { putReport } from "@/server/report-store";

/**
 * Turns a `submit_report` tool call into a real Report: stored, PDF-backed,
 * and sitting in the CEO's review queue with a notification behind it.
 *
 * The parts the model writes (summary, metrics, findings, risks, decisions)
 * are taken as given; everything structural — department and project results,
 * contributions, appendix — is filled from actual company state so the report
 * cannot drift from reality.
 */

let seq = 0;
const uid = (prefix: string) => `${prefix}-${Date.now().toString(36)}-${(seq++).toString(36)}`;

const roleOf = (id: string) => AGENTS_BY_ID[id]?.role ?? id;

function asStringArray(value: unknown): string[] {
  return Array.isArray(value) ? value.filter((v): v is string => typeof v === "string") : [];
}

export function submitReportFromAgent(
  input: Record<string, unknown>,
  agentId: string,
  now: number,
): Report {
  const type = (String(input.type ?? "executive") as ReportType) ?? "executive";
  const projectId = input.projectId ? String(input.projectId) : undefined;
  const departmentId = input.departmentId ? String(input.departmentId) : undefined;

  const state = read((s) => s);

  const scopedTasks = state.tasks.filter((t) =>
    projectId ? t.project === projectId : departmentId ? t.department === departmentId : true,
  );

  const departments: DepartmentId[] = departmentId
    ? [departmentId as DepartmentId]
    : projectId
      ? (PROJECTS_BY_ID[projectId]?.departments ?? [])
      : DEPARTMENTS.map((d) => d.id);

  const content: ReportContent = {
    subtitle: `${
      projectId
        ? (PROJECTS_BY_ID[projectId]?.name ?? projectId)
        : departmentId
          ? (DEPARTMENTS.find((d) => d.id === departmentId)?.name ?? departmentId)
          : "全社"
    } — ${REPORT_TYPE_LABEL[type]}`,
    period: formatDate(now),
    executiveSummary: String(input.executiveSummary ?? ""),

    keyMetrics: Array.isArray(input.keyMetrics)
      ? (input.keyMetrics as Record<string, unknown>[]).slice(0, 8).map((m) => ({
          label: String(m.label ?? ""),
          value: String(m.value ?? ""),
          delta: m.delta ? String(m.delta) : undefined,
          positive: m.delta ? !String(m.delta).startsWith("-") : undefined,
        }))
      : [],

    // Structural sections come from real state, not from the model.
    departmentResults: departments.map((id) => {
      const meta = DEPARTMENTS.find((d) => d.id === id)!;
      const tasks = scopedTasks.filter((t) => t.department === id);
      const done = tasks.filter((t) => t.status === "COMPLETED").length;
      const open = tasks.filter((t) => t.status !== "COMPLETED" && t.status !== "FAILED");
      return {
        department: id,
        headline: meta.mandate,
        points: [
          `完了 ${done} 件 / 進行中 ${open.length} 件。`,
          ...(open[0] ? [`最優先は「${open[0].title}」（${roleOf(open[0].assignedAgent)}）。`] : []),
        ],
      };
    }),

    projectResults: (projectId ? [projectId] : Object.keys(PROJECTS_BY_ID)).map((id) => {
      const p = PROJECTS_BY_ID[id];
      const next = p.milestones.find((m) => !m.done);
      return {
        projectId: id,
        progress: p.progress,
        health: p.health,
        note: next ? `次は「${next.label}」。` : "全マイルストーン完了。",
      };
    }),

    achievements: state.activity
      .filter((e) => e.kind === "agent.completed" || e.kind === "task.completed")
      .slice(0, 6)
      .map((e) => ({
        agentId: e.agentId,
        text: e.detail ? `${e.message} — ${e.detail}` : e.message,
      })),

    findings: asStringArray(input.findings),

    risks: Array.isArray(input.risks)
      ? (input.risks as Record<string, unknown>[]).slice(0, 6).map((r) => ({
          level: (String(r.level ?? "medium") as "high" | "medium" | "low") ?? "medium",
          text: String(r.text ?? ""),
        }))
      : [],

    decisions: asStringArray(input.decisions).length
      ? asStringArray(input.decisions)
      : ["現時点でCEOの判断を要する事項はありません。"],

    nextActions: asStringArray(input.nextActions),

    appendix: [
      { label: "Generated by", value: roleOf(agentId) },
      { label: "Mode", value: "Live — Claude API" },
      { label: "Data sources", value: "Tasks · Activity · Projects · Departments · Analytics" },
      { label: "Approval gate", value: "送信・公開・課金・本番反映はCEO承認を要します" },
    ],
  };

  const id = uid("rep");
  const sources = [
    agentId,
    ...new Set(content.achievements.map((a) => a.agentId)),
  ].slice(0, 10);

  const report: Report = {
    id,
    title: String(input.title ?? `${REPORT_TYPE_LABEL[type]} — ${formatDate(now)}`),
    type,
    status: "PENDING_REVIEW",
    createdBy: agentId,
    sources,
    createdAt: now,
    updatedAt: now,
    projectId,
    departmentId: departmentId as DepartmentId | undefined,
    content,
    pdfUrl: `/reports/${id}/pdf`,
    requiresReview: true,
    priority: (content.risks.some((r) => r.level === "high") ? "high" : "medium") as Priority,
    version: 1,
  };

  const approvalId = uid("ap");
  report.approvalId = approvalId;

  mutate((s) => {
    s.reports = [report, ...s.reports];
    s.approvals = [
      {
        id: approvalId,
        kind: "report",
        title: `${report.title} の確認`,
        description: content.executiveSummary.slice(0, 160),
        requestedBy: agentId,
        requestedAt: now,
        summary: `${sources.length}名のAI社員の成果を集約しました。PDFを添付しています。`,
        impact: "承認するとレポートが確定し、Knowledge Center へ保存されます。",
        risk: "low",
        priority: report.priority,
        status: "pending",
        relatedReportId: id,
        href: `/reports/${id}`,
        payload: [
          { label: "Type", value: REPORT_TYPE_LABEL[type] },
          { label: "Created by", value: roleOf(agentId) },
          { label: "PDF", value: report.pdfUrl },
        ],
      },
      ...s.approvals,
    ];
    s.notifications = [
      {
        id: uid("ntf"),
        kind: "report",
        level: "APPROVAL_REQUIRED",
        title: `${report.title} is ready for review.`,
        message: `${roleOf(agentId)}がレポートを作成しました。PDFを確認のうえ承認してください。`,
        createdAt: now,
        read: false,
        recipient: "CEO",
        agentId,
        relatedReportId: id,
        relatedApprovalId: approvalId,
        href: `/reports/${id}`,
        actionLabel: "Open Report",
      },
      ...s.notifications,
    ];
    s.activity = [
      {
        id: uid("act"),
        kind: "report.generated",
        agentId,
        at: now,
        message: `${REPORT_TYPE_LABEL[type]}を生成`,
        detail: report.title,
        reportId: id,
        severity: "important",
      },
      ...s.activity,
    ];
  });

  // Register with the PDF route so the URL resolves immediately.
  putReport(report);

  return report;
}
