"use client";

import Link from "next/link";
import { useState } from "react";
import { motion } from "framer-motion";
import { AlertTriangle, ArrowRight, Sparkles, Sunrise } from "lucide-react";
import { AGENTS_BY_ID } from "@/lib/company/agents";
import { DAILY_REPORT, MORNING_BRIEFING, NEXT_SCHEDULED } from "@/lib/company/reports";
import { useCompany } from "@/lib/store";
import { formatCountdown, formatDate, formatTime } from "@/lib/time";
import { cn } from "@/lib/utils";
import { Avatar, Button, Chip, Panel, PanelHeader } from "@/components/ui/primitives";
import { PageHeader } from "@/components/ui/page-header";

type Tab = "daily" | "morning";

export default function ReportsPage() {
  const now = useCompany((s) => s.now);
  const schedule = useCompany((s) => s.schedule);
  const [tab, setTab] = useState<Tab>("daily");

  return (
    <div className="space-y-5">
      <PageHeader
        eyebrow={<span className="label">Scheduled Intelligence</span>}
        title="Reports"
        description="AI会社が毎日あなたのために生成する、朝のブリーフィングと夜の経営報告。"
        actions={
          <div className="flex gap-1">
            <Button
              variant={tab === "daily" ? "primary" : "outline"}
              size="sm"
              onClick={() => setTab("daily")}
            >
              Daily Executive
            </Button>
            <Button
              variant={tab === "morning" ? "primary" : "outline"}
              size="sm"
              onClick={() => setTab("morning")}
            >
              Morning Briefing
            </Button>
          </div>
        }
      />

      <div className="grid gap-px overflow-hidden rounded-2xl border border-hairline bg-hairline sm:grid-cols-3">
        <ScheduleCell
          label="Morning Briefing"
          time={schedule.morningBriefing}
          next={formatCountdown(NEXT_SCHEDULED.morningBriefing, now)}
        />
        <ScheduleCell
          label="Daily Executive Report"
          time={schedule.dailyReport}
          next={formatCountdown(NEXT_SCHEDULED.dailyReport, now)}
        />
        <ScheduleCell
          label="Weekly Board Meeting"
          time={`${schedule.weeklyBoardDay} ${schedule.weeklyBoard}`}
          next={formatCountdown(NEXT_SCHEDULED.boardMeeting, now)}
        />
      </div>

      {tab === "daily" ? <DailyReport /> : <MorningBriefing />}
    </div>
  );
}

function ScheduleCell({ label, time, next }: { label: string; time: string; next: string }) {
  return (
    <div className="bg-surface/70 px-5 py-4">
      <div className="label">{label}</div>
      <div className="num mt-1.5 text-lg font-semibold leading-none text-ink">{time}</div>
      <div className="mt-1 text-[10px] text-ink-ghost">next in {next}</div>
    </div>
  );
}

function DailyReport() {
  const now = useCompany((s) => s.now);

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35 }}
      id="daily"
      className="space-y-5"
    >
      <Panel className="overflow-hidden">
        <PanelHeader
          title="Daily Executive Report"
          hint={formatDate(now)}
          action={
            <Chip className="bg-accent/12 text-accent-soft">
              Generated by COO
            </Chip>
          }
        />

        <div className="grid grid-cols-2 gap-px bg-hairline md:grid-cols-5">
          {DAILY_REPORT.metrics.map((m) => (
            <div key={m.label} className="bg-surface/70 px-5 py-4">
              <div className="label">{m.label}</div>
              <div className="mt-1.5 flex items-baseline gap-2">
                <span className="num text-2xl font-semibold leading-none tracking-tight text-ink">
                  {m.value}
                </span>
                <span
                  className={cn(
                    "num text-[10px] font-medium",
                    m.delta.startsWith("-") ? "text-live" : "text-live",
                  )}
                >
                  {m.delta}
                </span>
              </div>
            </div>
          ))}
        </div>

        <div className="border-t border-hairline px-5 py-5 lg:px-7 lg:py-6">
          <span className="label">Today&rsquo;s summary</span>
          <p className="mt-2.5 max-w-4xl text-sm leading-[1.85] text-ink-muted">
            {DAILY_REPORT.summary}
          </p>
        </div>
      </Panel>

      <div className="grid gap-5 lg:grid-cols-[minmax(0,1.3fr)_minmax(0,1fr)]">
        <Panel className="overflow-hidden">
          <PanelHeader title="Highlights" hint="部署別の主要成果" />
          <ul className="divide-y divide-hairline">
            {DAILY_REPORT.highlights.map((h, i) => {
              const agent = AGENTS_BY_ID[h.agentId];
              return (
                <li key={i} className="flex items-start gap-3 px-5 py-3.5">
                  {agent && <Avatar name={agent.name} accent={agent.accent} size="sm" />}
                  <div className="min-w-0 flex-1">
                    <Link
                      href={agent ? `/employees/${agent.id}` : "#"}
                      className="text-[11px] font-semibold text-ink transition-colors hover:text-accent-soft"
                    >
                      {agent?.role ?? h.agentId}
                    </Link>
                    <p className="mt-0.5 text-xs leading-relaxed text-ink-muted">{h.text}</p>
                  </div>
                </li>
              );
            })}
          </ul>
        </Panel>

        <div className="space-y-5">
          <Panel className="overflow-hidden">
            <PanelHeader title="Risks" hint="注意が必要な事項" />
            <ul className="divide-y divide-hairline">
              {DAILY_REPORT.risks.map((r, i) => (
                <li key={i} className="flex items-start gap-3 px-5 py-3.5">
                  <AlertTriangle
                    className={cn(
                      "mt-0.5 h-3.5 w-3.5 shrink-0",
                      r.level === "high" ? "text-danger" : "text-warn",
                    )}
                    strokeWidth={1.75}
                  />
                  <p className="text-xs leading-relaxed text-ink-muted">{r.text}</p>
                </li>
              ))}
            </ul>
          </Panel>

          <Panel className="overflow-hidden">
            <PanelHeader
              title="Tomorrow's recommended actions"
              action={<Sparkles className="h-3.5 w-3.5 text-accent-soft" strokeWidth={1.75} />}
            />
            <ul className="divide-y divide-hairline">
              {DAILY_REPORT.tomorrow.map((t, i) => (
                <li key={i} className="flex items-start gap-3 px-5 py-3">
                  <span className="num mt-0.5 shrink-0 text-[10px] text-ink-ghost">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <p className="text-xs leading-relaxed text-ink-muted">{t}</p>
                </li>
              ))}
            </ul>
          </Panel>
        </div>
      </div>
    </motion.div>
  );
}

function MorningBriefing() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35 }}
      id="morning"
      className="space-y-5"
    >
      <Panel className="relative overflow-hidden">
        <div
          className="pointer-events-none absolute -right-24 -top-28 h-72 w-72 rounded-full bg-warn/10 blur-[100px]"
          aria-hidden
        />
        <div className="relative px-5 py-6 lg:px-8 lg:py-8">
          <div className="flex items-center gap-2">
            <Sunrise className="h-4 w-4 text-warn" strokeWidth={1.75} />
            <span className="label text-warn">Morning Briefing</span>
            <span className="num text-[10px] text-ink-ghost">
              · generated {formatTime(MORNING_BRIEFING.generatedAt)}
            </span>
          </div>
          <p className="mt-3 max-w-3xl text-lg font-medium leading-relaxed tracking-tight text-ink lg:text-xl">
            {MORNING_BRIEFING.opening}
          </p>
        </div>
      </Panel>

      <div className="relative">
        <span
          className="pointer-events-none absolute bottom-6 left-[18px] top-6 w-px bg-hairline lg:left-[22px]"
          aria-hidden
        />
        <ol className="space-y-3">
          {MORNING_BRIEFING.sections.map((section, i) => {
            const agent = AGENTS_BY_ID[section.agentId];
            return (
              <motion.li
                key={section.label}
                initial={{ opacity: 0, x: -6 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.3, delay: i * 0.06 }}
                className="relative flex gap-4"
              >
                <span className="relative z-10 mt-3 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-hairline bg-surface lg:h-11 lg:w-11">
                  {agent ? (
                    <Avatar name={agent.name} accent={agent.accent} size="sm" />
                  ) : (
                    <ArrowRight className="h-3.5 w-3.5 text-ink-ghost" strokeWidth={1.75} />
                  )}
                </span>

                <Panel className="min-w-0 flex-1 px-5 py-4">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="label">{section.label}</span>
                    {agent && (
                      <Link
                        href={`/employees/${agent.id}`}
                        className="text-[10px] text-ink-ghost transition-colors hover:text-accent-soft"
                      >
                        {agent.role}
                      </Link>
                    )}
                  </div>
                  <ul className="mt-2 space-y-1.5">
                    {section.lines.map((line, li) => (
                      <li key={li} className="flex items-start gap-2.5">
                        <span className="mt-[7px] h-1 w-1 shrink-0 rounded-full bg-accent/60" />
                        <span className="text-xs leading-relaxed text-ink-muted">{line}</span>
                      </li>
                    ))}
                  </ul>
                </Panel>
              </motion.li>
            );
          })}
        </ol>
      </div>
    </motion.div>
  );
}
