"use client";

import Link from "next/link";
import { notFound, useParams } from "next/navigation";
import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import {
  AlertTriangle,
  Check,
  FileText,
  Maximize2,
  MessageSquareWarning,
  X,
} from "lucide-react";
import { AGENTS_BY_ID } from "@/lib/company/agents";
import { DEPARTMENTS } from "@/lib/company/departments";
import { PROJECTS_BY_ID } from "@/lib/company/projects";
import { useCompany } from "@/lib/store";
import { formatDate, formatRelative, formatTime } from "@/lib/time";
import { cn } from "@/lib/utils";
import { REPORT_TYPE_LABEL } from "@/lib/types";
import {
  Avatar,
  Button,
  Chip,
  Panel,
  PanelHeader,
  Progress,
} from "@/components/ui/primitives";
import { PageHeader } from "@/components/ui/page-header";
import { PdfLink, ReportStatusChip } from "@/components/reports/report-bits";
import { DepartmentTag } from "@/components/company/department-tag";

export default function ReportDetailPage() {
  const params = useParams<{ id: string }>();
  const id = params?.id;

  const reports = useCompany((s) => s.reports);
  const now = useCompany((s) => s.now);
  const decide = useCompany((s) => s.decideReport);

  const [revising, setRevising] = useState(false);
  const [comment, setComment] = useState("");
  const [preview, setPreview] = useState(true);

  const report = reports.find((r) => r.id === id);
  if (!id) notFound();
  if (!report) {
    return (
      <div className="space-y-5">
        <PageHeader backHref="/reports" backLabel="Report Center" title="Report not found" />
        <Panel className="px-5 py-12 text-center">
          <p className="text-sm text-ink-muted">このレポートは存在しません。</p>
          <p className="mt-1.5 text-xs text-ink-ghost">
            サーバー再起動後、実行時に生成したレポートは失われます（Phase 3 で永続化）。
          </p>
        </Panel>
      </div>
    );
  }

  const author = AGENTS_BY_ID[report.createdBy];
  const c = report.content;
  const pending = report.status === "PENDING_REVIEW";
  const previousVersion = report.revisionOf
    ? reports.find((r) => r.id === report.revisionOf)
    : undefined;
  const supersededBy = reports.find((r) => r.revisionOf === report.id);

  function submitRevision() {
    if (!comment.trim()) return;
    decide(report!.id, "REVISION_REQUIRED", comment.trim());
    setRevising(false);
    setComment("");
  }

  return (
    <div className="space-y-5">
      <PageHeader
        backHref="/reports"
        backLabel="Report Center"
        eyebrow={
          <div className="flex flex-wrap items-center gap-2">
            <ReportStatusChip status={report.status} />
            <Chip>{REPORT_TYPE_LABEL[report.type]}</Chip>
            {report.version > 1 && (
              <Chip className="bg-[#A78BFA]/12 text-[#A78BFA]">version {report.version}</Chip>
            )}
          </div>
        }
        title={report.title}
        description={c.subtitle}
        actions={<PdfLink report={report} variant="button" />}
      />

      {/* Version trail */}
      {(previousVersion || supersededBy) && (
        <div className="flex flex-wrap items-center gap-3 rounded-xl border border-[#A78BFA]/25 bg-[#A78BFA]/[0.06] px-4 py-2.5">
          <MessageSquareWarning className="h-3.5 w-3.5 shrink-0 text-[#A78BFA]" strokeWidth={1.75} />
          {previousVersion && (
            <span className="text-2xs text-ink-muted">
              これは修正依頼を受けて再作成された v{report.version} です。
              <Link
                href={`/reports/${previousVersion.id}`}
                className="ml-1.5 text-[#A78BFA] hover:underline"
              >
                v{previousVersion.version} を見る
              </Link>
            </span>
          )}
          {supersededBy && (
            <span className="text-2xs text-ink-muted">
              このレポートは修正版に置き換えられています。
              <Link
                href={`/reports/${supersededBy.id}`}
                className="ml-1.5 text-[#A78BFA] hover:underline"
              >
                v{supersededBy.version} を開く
              </Link>
            </span>
          )}
        </div>
      )}

      {/* Overview */}
      <div className="grid gap-px overflow-hidden rounded-2xl border border-hairline bg-hairline sm:grid-cols-2 xl:grid-cols-4">
        <Cell label="Generated by" value={author?.role ?? report.createdBy} />
        <Cell label="Period" value={c.period} />
        <Cell
          label="Created"
          value={`${formatDate(report.createdAt)} ${formatTime(report.createdAt)}`}
        />
        <Cell
          label="Confirmation"
          value={
            pending
              ? "Pending Review"
              : report.status === "APPROVED"
                ? "Approved"
                : report.status === "REJECTED"
                  ? "Rejected"
                  : report.status === "REVISION_REQUIRED"
                    ? "Revision requested"
                    : "—"
          }
          tone={
            pending
              ? "text-warn"
              : report.status === "APPROVED"
                ? "text-live"
                : report.status === "REJECTED"
                  ? "text-danger"
                  : undefined
          }
        />
      </div>

      <div className="grid gap-5 xl:grid-cols-[minmax(0,1.45fr)_minmax(0,1fr)]">
        <div className="space-y-5">
          {/* Executive summary */}
          <Panel className="overflow-hidden">
            <PanelHeader title="Executive Summary" />
            <p className="px-5 py-5 text-sm leading-[1.9] text-ink-muted lg:px-7">
              {c.executiveSummary}
            </p>
          </Panel>

          {/* Metrics */}
          {c.keyMetrics.length > 0 && (
            <Panel className="overflow-hidden">
              <PanelHeader title="Key Metrics" />
              <div className="grid grid-cols-2 gap-px bg-hairline md:grid-cols-3 xl:grid-cols-5">
                {c.keyMetrics.map((m) => (
                  <div key={m.label} className="bg-surface/70 px-4 py-3.5">
                    <div className="label">{m.label}</div>
                    <div className="mt-1.5 flex items-baseline gap-1.5">
                      <span className="num text-xl font-semibold leading-none text-ink">
                        {m.value}
                      </span>
                      {m.delta && (
                        <span
                          className={cn(
                            "num text-3xs font-medium",
                            m.positive === false ? "text-danger" : "text-live",
                          )}
                        >
                          {m.delta}
                        </span>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </Panel>
          )}

          {/* Departments */}
          {c.departmentResults.length > 0 && (
            <Panel className="overflow-hidden">
              <PanelHeader title="Department Results" />
              <ul className="divide-y divide-hairline">
                {c.departmentResults.map((d) => {
                  const meta = DEPARTMENTS.find((x) => x.id === d.department);
                  return (
                    <li key={d.department} className="px-5 py-3.5">
                      <div className="flex flex-wrap items-center gap-2">
                        <DepartmentTag
                          department={d.department}
                          href={`/departments/${d.department}`}
                        />
                        {d.metric && (
                          <span className="num ml-auto text-3xs text-ink-ghost">
                            {d.metric.label}: {d.metric.value}
                          </span>
                        )}
                      </div>
                      <p className="mt-1.5 text-xs leading-relaxed text-ink">{d.headline}</p>
                      <ul className="mt-1.5 space-y-1">
                        {d.points.map((p, i) => (
                          <li key={i} className="flex items-start gap-2">
                            <span className="mt-[7px] h-1 w-1 shrink-0 rounded-full bg-ink-ghost" />
                            <span className="text-2xs leading-relaxed text-ink-muted">{p}</span>
                          </li>
                        ))}
                      </ul>
                    </li>
                  );
                })}
              </ul>
            </Panel>
          )}

          {/* Projects */}
          {c.projectResults.length > 0 && (
            <Panel className="overflow-hidden">
              <PanelHeader title="Project Results" />
              <ul className="divide-y divide-hairline">
                {c.projectResults.map((p) => {
                  const project = PROJECTS_BY_ID[p.projectId];
                  const tone =
                    p.health === "on_track" ? "live" : p.health === "at_risk" ? "warn" : "danger";
                  return (
                    <li key={p.projectId} className="px-5 py-3">
                      <div className="flex items-center gap-3">
                        <Link
                          href={`/projects/${p.projectId}`}
                          className="text-[12px] font-medium text-ink transition-colors hover:text-accent-soft"
                        >
                          {project?.name ?? p.projectId}
                        </Link>
                        <span
                          className={cn(
                            "num ml-auto text-2xs font-semibold",
                            tone === "live"
                              ? "text-live"
                              : tone === "warn"
                                ? "text-warn"
                                : "text-danger",
                          )}
                        >
                          {p.progress}%
                        </span>
                      </div>
                      <Progress value={p.progress} tone={tone} className="mt-2" />
                      <p className="mt-1.5 text-2xs text-ink-faint">{p.note}</p>
                    </li>
                  );
                })}
              </ul>
            </Panel>
          )}

          {/* Contributions */}
          {c.achievements.length > 0 && (
            <Panel className="overflow-hidden">
              <PanelHeader title="AI Employee Contributions" />
              <ul className="divide-y divide-hairline">
                {c.achievements.map((a, i) => {
                  const agent = AGENTS_BY_ID[a.agentId];
                  return (
                    <li key={i} className="flex items-start gap-3 px-5 py-3">
                      {agent && <Avatar name={agent.name} accent={agent.accent} size="sm" />}
                      <div className="min-w-0 flex-1">
                        <Link
                          href={agent ? `/employees/${agent.id}` : "#"}
                          className="text-2xs font-semibold text-ink transition-colors hover:text-accent-soft"
                        >
                          {agent?.role ?? a.agentId}
                        </Link>
                        <p className="mt-0.5 text-xs leading-relaxed text-ink-muted">{a.text}</p>
                      </div>
                    </li>
                  );
                })}
              </ul>
            </Panel>
          )}

          {/* Findings & risks */}
          <div className="grid gap-5 lg:grid-cols-2">
            {c.findings.length > 0 && (
              <Panel className="overflow-hidden">
                <PanelHeader title="Important Findings" />
                <ul className="divide-y divide-hairline">
                  {c.findings.map((f, i) => (
                    <li key={i} className="px-5 py-2.5 text-2xs leading-relaxed text-ink-muted">
                      {f}
                    </li>
                  ))}
                </ul>
              </Panel>
            )}

            {c.risks.length > 0 && (
              <Panel className="overflow-hidden">
                <PanelHeader title="Problems / Risks" />
                <ul className="divide-y divide-hairline">
                  {c.risks.map((r, i) => (
                    <li key={i} className="flex items-start gap-2.5 px-5 py-3">
                      <AlertTriangle
                        className={cn(
                          "mt-0.5 h-3.5 w-3.5 shrink-0",
                          r.level === "high" ? "text-danger" : "text-warn",
                        )}
                        strokeWidth={1.75}
                      />
                      <p className="text-2xs leading-relaxed text-ink-muted">{r.text}</p>
                    </li>
                  ))}
                </ul>
              </Panel>
            )}
          </div>

          {/* Decisions + next actions */}
          <Panel className="overflow-hidden">
            <PanelHeader title="CEO Decisions Required" hint={`${c.decisions.length}`} />
            <ul className="divide-y divide-hairline">
              {c.decisions.map((d, i) => (
                <li key={i} className="flex items-start gap-3 px-5 py-3">
                  <span className="num shrink-0 text-3xs text-accent-soft">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <span className="text-xs leading-relaxed text-ink-muted">{d}</span>
                </li>
              ))}
            </ul>
          </Panel>

          {c.nextActions.length > 0 && (
            <Panel className="overflow-hidden">
              <PanelHeader title="Next Actions" />
              <ul className="divide-y divide-hairline">
                {c.nextActions.map((a, i) => (
                  <li key={i} className="flex items-start gap-3 px-5 py-3">
                    <span className="num shrink-0 text-3xs text-ink-ghost">
                      {String(i + 1).padStart(2, "0")}
                    </span>
                    <span className="text-xs leading-relaxed text-ink-muted">{a}</span>
                  </li>
                ))}
              </ul>
            </Panel>
          )}
        </div>

        {/* ── Right rail: PDF + CEO decision ─────────────────────────────── */}
        <div className="space-y-5">
          <Panel className="overflow-hidden">
            <PanelHeader
              title="PDF"
              hint={pending ? "確認が必要です" : undefined}
              action={
                <button
                  onClick={() => setPreview((v) => !v)}
                  className="font-mono text-3xs uppercase tracking-[0.14em] text-ink-ghost transition-colors hover:text-accent-soft"
                >
                  {preview ? "Hide preview" : "Show preview"}
                </button>
              }
            />
            <div className="space-y-3 px-5 py-4">
              <div>
                <span className="label">PDF URL</span>
                <div className="mt-1.5">
                  <PdfLink report={report} variant="url" />
                </div>
              </div>

              <AnimatePresence initial={false}>
                {preview && (
                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: "auto" }}
                    exit={{ opacity: 0, height: 0 }}
                    transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
                    className="overflow-hidden"
                  >
                    <div className="relative overflow-hidden rounded-xl border border-hairline bg-white/[0.02]">
                      <iframe
                        src={`${report.pdfUrl}#toolbar=0&navpanes=0&view=FitH`}
                        title={`${report.title} PDF preview`}
                        className="h-[520px] w-full bg-white"
                      />
                      <a
                        href={report.pdfUrl}
                        target="_blank"
                        rel="noreferrer"
                        className="absolute right-2 top-2 inline-flex items-center gap-1 rounded-lg bg-black/70 px-2 py-1 font-mono text-3xs uppercase tracking-[0.14em] text-white backdrop-blur transition-colors hover:bg-black/85"
                      >
                        <Maximize2 className="h-2.5 w-2.5" strokeWidth={2} />
                        Full
                      </a>
                    </div>
                    <p className="mt-2 text-3xs leading-relaxed text-ink-ghost">
                      プレビューはブラウザ内蔵のPDFビューアで表示しています。表示されない場合は
                      Open PDF から別タブで開いてください。
                    </p>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          </Panel>

          {/* CEO decision */}
          <Panel
            className={cn(
              "overflow-hidden",
              pending && "border-warn/25 shadow-[0_0_0_1px_rgba(229,168,75,0.12)]",
            )}
          >
            <PanelHeader
              title="CEO Decision"
              hint={pending ? "あなたの判断を待っています" : "決定済み"}
            />
            <div className="px-5 py-4">
              {pending ? (
                <>
                  <p className="text-2xs leading-relaxed text-ink-muted">
                    承認すると確定版として保存されます。修正依頼を出すと、
                    {author?.role ?? "担当AI社員"}が修正版を作成します。
                  </p>

                  <AnimatePresence initial={false} mode="wait">
                    {revising ? (
                      <motion.div
                        key="revise"
                        initial={{ opacity: 0, y: -4 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0 }}
                        transition={{ duration: 0.2 }}
                        className="mt-3"
                      >
                        <label className="label" htmlFor="revision-comment">
                          修正依頼の内容
                        </label>
                        <textarea
                          id="revision-comment"
                          value={comment}
                          onChange={(e) => setComment(e.target.value)}
                          rows={3}
                          autoFocus
                          placeholder="例: 営業部の成果についてもっと詳しく"
                          className="mt-1.5 w-full resize-none rounded-lg border border-hairline bg-white/[0.03] px-3 py-2 text-xs leading-relaxed text-ink placeholder:text-ink-ghost focus:border-accent-line focus:outline-none"
                        />
                        <div className="mt-2 flex items-center gap-1.5">
                          <Button
                            variant="primary"
                            size="sm"
                            onClick={submitRevision}
                            disabled={!comment.trim()}
                          >
                            修正を依頼
                          </Button>
                          <Button variant="ghost" size="sm" onClick={() => setRevising(false)}>
                            Cancel
                          </Button>
                        </div>
                      </motion.div>
                    ) : (
                      <motion.div
                        key="actions"
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        className="mt-3 flex flex-wrap items-center gap-1.5"
                      >
                        <Button
                          variant="success"
                          size="sm"
                          onClick={() => decide(report.id, "APPROVED")}
                        >
                          <Check className="h-3 w-3" strokeWidth={2.25} />
                          Approve
                        </Button>
                        <Button variant="outline" size="sm" onClick={() => setRevising(true)}>
                          <MessageSquareWarning className="h-3 w-3" strokeWidth={1.75} />
                          Request Revision
                        </Button>
                        <Button
                          variant="danger"
                          size="sm"
                          onClick={() => decide(report.id, "REJECTED")}
                        >
                          <X className="h-3 w-3" strokeWidth={2.25} />
                          Reject
                        </Button>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </>
              ) : (
                <div className="space-y-2">
                  <div className="flex items-center gap-2">
                    <ReportStatusChip status={report.status} />
                    {report.reviewedAt && (
                      <span className="num text-3xs text-ink-ghost">
                        {formatRelative(report.reviewedAt, now)}
                      </span>
                    )}
                  </div>
                  {report.reviewedBy && (
                    <p className="text-2xs text-ink-muted">
                      Reviewed by <span className="text-ink">{report.reviewedBy}</span>
                    </p>
                  )}
                  {report.reviewComment && (
                    <p className="rounded-lg border border-hairline bg-white/[0.02] px-3 py-2 text-2xs leading-relaxed text-ink-muted">
                      「{report.reviewComment}」
                    </p>
                  )}
                </div>
              )}
            </div>
          </Panel>

          {/* Sources */}
          <Panel className="overflow-hidden">
            <PanelHeader title="Sources" hint={`${report.sources.length} AI employees`} />
            <ul className="divide-y divide-hairline">
              {report.sources.map((sid) => {
                const agent = AGENTS_BY_ID[sid];
                if (!agent) return null;
                return (
                  <li key={sid}>
                    <Link
                      href={`/employees/${agent.id}`}
                      className="flex items-center gap-2.5 px-5 py-2.5 transition-colors hover:bg-white/[0.025]"
                    >
                      <Avatar name={agent.name} accent={agent.accent} size="xs" status={agent.status} />
                      <span className="flex-1 truncate text-2xs text-ink-muted">
                        {agent.role}
                      </span>
                      <span className="font-mono text-3xs uppercase tracking-[0.14em] text-ink-ghost">
                        {agent.department}
                      </span>
                    </Link>
                  </li>
                );
              })}
            </ul>
          </Panel>

          {/* Appendix */}
          <Panel className="overflow-hidden">
            <PanelHeader
              title="Appendix"
              action={<FileText className="h-3.5 w-3.5 text-ink-ghost" strokeWidth={1.75} />}
            />
            <dl className="divide-y divide-hairline">
              {c.appendix.map((row) => (
                <div key={row.label} className="flex gap-4 px-5 py-2.5">
                  <dt className="w-28 shrink-0 font-mono text-3xs uppercase tracking-[0.14em] text-ink-ghost">
                    {row.label}
                  </dt>
                  <dd className="min-w-0 flex-1 text-2xs text-ink-muted">{row.value}</dd>
                </div>
              ))}
            </dl>
          </Panel>
        </div>
      </div>
    </div>
  );
}

function Cell({ label, value, tone }: { label: string; value: string; tone?: string }) {
  return (
    <div className="bg-surface/70 px-5 py-3.5">
      <div className="label">{label}</div>
      <div className={cn("mt-1 text-[13px] font-medium", tone ?? "text-ink")}>{value}</div>
    </div>
  );
}
