import { DAILY_REPORT, MORNING_BRIEFING, BOARD_MEETINGS } from "./reports";
import { DEPARTMENT_LOAD } from "./analytics";
import { DEPARTMENTS } from "./departments";
import { PROJECTS_BY_ID } from "./projects";
import { ago, days, formatDate, hours, minutes, SEED_NOW } from "@/lib/time";
import type { Report, ReportContent, ReportDepartmentResult } from "@/lib/types";

/**
 * The reports the company has already produced.
 *
 * These reuse the hand-authored Daily Report and Morning Briefing content
 * rather than duplicating it, so the narrative the dashboard has always shown
 * is now a first-class Report entity with a PDF, a status and a review trail.
 */

const pdf = (id: string) => `/reports/${id}/pdf`;

function deptResults(ids: string[]): ReportDepartmentResult[] {
  return ids
    .map((id) => DEPARTMENTS.find((d) => d.id === id))
    .filter((d): d is (typeof DEPARTMENTS)[number] => Boolean(d))
    .map((d) => {
      const load = DEPARTMENT_LOAD.find((l) => l.department === d.id);
      return {
        department: d.id,
        headline: d.mandate,
        points: [
          `稼働 ${load?.active ?? 0} 名 / 完了 ${load?.completed ?? 0} 件。`,
          `稼働率 ${load?.utilization ?? 0}%。`,
        ],
        metric: load ? { label: "Utilization", value: `${load.utilization}%` } : undefined,
      };
    });
}

/* ── 1. Daily Executive Report — the flagship, awaiting the CEO ───────────── */

const dailyContent: ReportContent = {
  subtitle: "全社 — Daily Executive Report",
  period: formatDate(SEED_NOW),
  executiveSummary: DAILY_REPORT.summary,
  keyMetrics: DAILY_REPORT.metrics.map((m) => ({
    label: m.label,
    value: m.value,
    delta: m.delta,
    positive: !m.delta.startsWith("-") || m.label.includes("Decisions"),
  })),
  departmentResults: deptResults([
    "marketing", "engineering", "sales", "research", "finance", "creative",
  ]),
  projectResults: ["re_palette", "friday", "newtone", "university"].map((id) => {
    const p = PROJECTS_BY_ID[id];
    const next = p.milestones.find((m) => !m.done);
    return {
      projectId: id,
      progress: p.progress,
      health: p.health,
      note: next ? `次は「${next.label}」。` : "全マイルストーン完了。",
    };
  }),
  achievements: DAILY_REPORT.highlights.map((h) => ({ agentId: h.agentId, text: h.text })),
  findings: [
    "Research Director: 関連する市場レポートを12件発見（うち一次情報は7件）",
    "Competitive Intel AI: 競合A社の求人情報から新規事業参入の兆候を検知",
    "Trend AI: Z世代の情報接触はSNS起点が78%、購買前の平均接触回数は5.4回",
    "Insight AI: 週次KPIで外れ値となる指標を3件抽出",
    "Cost Optimization AI: 機能が重複するSaaS契約を2件検出",
    "Market Research AI: 想定より高成長のセグメントを1つ特定",
  ],
  risks: DAILY_REPORT.risks.map((r) => ({ level: r.level, text: r.text })),
  decisions: [
    "本番環境へのDeploy — 認証基盤を含むビルドの反映可否（Infrastructure AI）",
    "Instagram 投稿3案の公開 — 本日18:00の予約投稿可否（Social Media AI）",
  ],
  nextActions: DAILY_REPORT.tomorrow,
  appendix: [
    { label: "Generated by", value: "COO" },
    { label: "Data sources", value: "Tasks · Activity · Projects · Departments · Analytics" },
    { label: "Reporting period", value: "2026-09-21 00:00 – 22:00 JST" },
    { label: "Approval gate", value: "送信・公開・課金・本番反映はCEO承認を要します" },
  ],
};

/* ── 2. Morning Briefing — already approved this morning ─────────────────── */

const briefingContent: ReportContent = {
  subtitle: "全社 — Morning Briefing",
  period: formatDate(SEED_NOW),
  executiveSummary: MORNING_BRIEFING.opening,
  keyMetrics: [
    { label: "Completed Yesterday", value: "48", delta: "+6", positive: true },
    { label: "AI Employees On Duty", value: "17" },
    { label: "Decisions For You", value: "2" },
    { label: "Signals Detected", value: "3" },
  ],
  departmentResults: deptResults(["marketing", "engineering", "sales"]),
  projectResults: ["friday", "re_palette"].map((id) => {
    const p = PROJECTS_BY_ID[id];
    return { projectId: id, progress: p.progress, health: p.health, note: p.summary };
  }),
  achievements: MORNING_BRIEFING.sections
    .filter((s) => s.label === "YESTERDAY")
    .flatMap((s) => s.lines.map((line) => ({ agentId: s.agentId, text: line }))),
  findings: MORNING_BRIEFING.sections.find((s) => s.label === "SIGNALS")?.lines ?? [],
  risks: [{ level: "medium", text: "大学出願書類の活動実績整理が未着手。残り5日。" }],
  decisions: MORNING_BRIEFING.sections.find((s) => s.label === "DECISIONS FOR YOU")?.lines ?? [],
  nextActions:
    MORNING_BRIEFING.sections.find((s) => s.label === "TODAY'S PRIORITIES")?.lines ?? [],
  appendix: [
    { label: "Generated by", value: "Executive Assistant" },
    { label: "Scheduled at", value: "08:00 JST" },
  ],
};

/* ── 3. Weekly Report — from the completed board meeting ─────────────────── */

const week37 = BOARD_MEETINGS.find((m) => m.status === "completed")!;

const weeklyContent: ReportContent = {
  subtitle: "全社 — Weekly Report",
  period: "2026-09-14 – 2026-09-20",
  executiveSummary: week37.summary,
  keyMetrics: [
    { label: "Weekly Throughput", value: "312", delta: "+9%", positive: true },
    { label: "Revenue (MTD)", value: "¥3,482,000", delta: "+12.4%", positive: true },
    { label: "New Leads", value: "186", delta: "+32.1%", positive: true },
    { label: "Followers", value: "248,532", delta: "+18.7%", positive: true },
    { label: "Primary Sources", value: "71%", delta: "+13pt", positive: true },
  ],
  departmentResults: week37.reports.map((r) => ({
    department:
      (DEPARTMENTS.find((d) => d.headAgentId === r.agentId)?.id ?? "strategy"),
    headline: r.headline,
    points: r.points,
    metric: r.metric ? { label: r.metric.label, value: r.metric.value, delta: r.metric.delta } : undefined,
  })),
  projectResults: Object.values(PROJECTS_BY_ID).map((p) => ({
    projectId: p.id,
    progress: p.progress,
    health: p.health,
    note: `${p.milestones.filter((m) => m.done).length}/${p.milestones.length} マイルストーン完了。`,
  })),
  achievements: week37.reports.map((r) => ({ agentId: r.agentId, text: r.headline })),
  findings: [
    "保存率は3週間後の流入と強く相関（0.71）。指標の切り替えが有効。",
    "ブロック中タスクの71%が認証基盤の完了待ちに集中している。",
    "一次情報の比率が58% → 71%へ改善した。",
  ],
  risks: [
    { level: "high", text: "NEWTONE 2027 が計画比で遅延。来週の最優先に指定。" },
    { level: "medium", text: "Engineering がクリティカルパス上にあり、遅延が全社へ波及する。" },
  ],
  decisions: week37.decisions,
  nextActions: [
    "開発リソースを20%増やす提案をCEOへ提出する。",
    "Re-Palette の指標をリーチから保存率へ切り替える。",
    "NEWTONE 2027 の集客導線をCreativeと再設計する。",
  ],
  appendix: [
    { label: "Generated by", value: "COO" },
    { label: "Meeting", value: week37.title },
    { label: "Directors reporting", value: String(week37.reports.length) },
  ],
};

/* ── 4-8. The rest of the shelf ──────────────────────────────────────────── */

const rePaletteProject = PROJECTS_BY_ID["re_palette"];

const projectContent: ReportContent = {
  subtitle: "Re-Palette — Project Report",
  period: formatDate(SEED_NOW),
  executiveSummary:
    "Re-Palette は進捗75%。SNSの保存率改善が3日連続で続き、提携候補18社の評価が完了しました。残るマイルストーンは「認知3倍施策」と「提携先3社確定」の2件で、いずれも期限は2週間以内です。提携先の確定には、初回接触メールの送信承認が前提になります。",
  keyMetrics: [
    { label: "Progress", value: "75%", delta: "+8pt", positive: true },
    { label: "Assigned AI Employees", value: String(rePaletteProject.agents.length) },
    { label: "Partnership Candidates", value: "18" },
    { label: "High-fit Candidates", value: "6" },
    { label: "Days To Deadline", value: "12" },
  ],
  departmentResults: deptResults(["marketing", "creative", "sales", "research"]),
  projectResults: [
    {
      projectId: "re_palette",
      progress: 75,
      health: "on_track",
      note: "次は「認知3倍施策」（9日後）。",
    },
  ],
  achievements: [
    { agentId: "cmo", text: "Instagram トレンド分析を完了。候補12件を抽出。" },
    { agentId: "lead_ai", text: "美容D2C企業リストを20件追加。" },
    { agentId: "cso", text: "提携候補18社を評価し、高適合6社を特定。" },
    { agentId: "designer_ai", text: "ランディングページのビジュアルを68%まで制作。" },
  ],
  findings: [
    "保存率の高い投稿は3週間後の流入に寄与する（相関 0.71）。",
    "競合が獲得していて自社が取れていない検索語を11件特定。",
  ],
  risks: [
    { level: "medium", text: "提携先3社の確定が、外部メール送信の承認待ちで止まっています。" },
  ],
  decisions: ["外部メール3通の送信可否（Outreach AI / CSOレビュー済み）"],
  nextActions: [
    "承認後、高適合6社へ優先順に初回接触する。",
    "LPのヘッドラインを保存率重視の訴求へ差し替える。",
  ],
  appendix: [
    { label: "Generated by", value: "COO" },
    { label: "Project", value: "Re-Palette" },
    { label: "Owner", value: "CMO" },
  ],
};

const researchContent: ReportContent = {
  subtitle: "Research — Research Report",
  period: formatDate(SEED_NOW),
  executiveSummary:
    "国内美容市場を一次統計から再推計したところ、市場規模は前年比+4.2%。サステナビリティ関連セグメントが最も高い成長率を示しており、Re-Palette の立ち位置と合致します。競合3社のうちA社に新規事業参入の兆候があり、先行の優位は限定的と判断します。",
  keyMetrics: [
    { label: "Market Growth", value: "+4.2%", positive: true },
    { label: "Reports Analysed", value: "12" },
    { label: "Primary Sources", value: "7" },
    { label: "Competitors Tracked", value: "3" },
  ],
  departmentResults: deptResults(["research"]),
  projectResults: [
    { projectId: "research_lab", progress: 61, health: "on_track", note: "一次情報ソースの拡充が進行中。" },
  ],
  achievements: [
    { agentId: "market_ai", text: "市場規模を一次統計から再推計。上振れセグメントを1つ特定。" },
    { agentId: "competitor_ai", text: "競合3社の動向を追跡し、A社の参入兆候を検知。" },
    { agentId: "trend_ai", text: "Z世代の購買前接触回数は平均5.4回と算出。" },
  ],
  findings: [
    "サステナビリティ関連セグメントの成長率が全体を上回る。",
    "競合A社の求人内容から、新規事業の立ち上げ準備が推定される。",
    "情報接触はSNS起点が78%を占める。",
  ],
  risks: [{ level: "medium", text: "競合A社の参入により、先行優位の期間が短くなる可能性。" }],
  decisions: ["現時点でCEOの判断を要する事項はありません。"],
  nextActions: [
    "A社の動きを週次で追跡し、変化があれば即時報告する。",
    "サステナビリティ軸の訴求をMarketingへ引き渡す。",
  ],
  appendix: [
    { label: "Generated by", value: "Research Director" },
    { label: "Method", value: "一次統計 + 競合公開情報 + SNS行動データ" },
  ],
};

const departmentContent: ReportContent = {
  subtitle: "Marketing — Department Report",
  period: formatDate(SEED_NOW),
  executiveSummary:
    "Marketing はリーチ重視から保存率重視への転換点にあります。フォロワーは+18.7%と伸びている一方、保存率は-4.2%。保存率は3週間後の流入と強く相関するため、認知3倍の目標には保存率の方が効きます。施策の待機時間が18%あり、Development への一時的なリソース移動の余地があります。",
  keyMetrics: [
    { label: "Followers", value: "248,532", delta: "+18.7%", positive: true },
    { label: "Save Rate", value: "-4.2%", delta: "-4.2%", positive: false },
    { label: "Idle Time", value: "18%" },
    { label: "Completed Tasks", value: "12" },
  ],
  departmentResults: deptResults(["marketing"]),
  projectResults: [
    { projectId: "re_palette", progress: 75, health: "on_track", note: "認知3倍施策が進行中。" },
  ],
  achievements: [
    { agentId: "cmo", text: "Instagram トレンド分析を完了。" },
    { agentId: "content_ai", text: "note記事の初稿を42%まで執筆。" },
    { agentId: "seo_ai", text: "競合キーワードギャップ分析を完了。" },
  ],
  findings: ["保存率の高い投稿は3週間後の流入に寄与する。"],
  risks: [{ level: "low", text: "施策の待機時間が18%。リソース配分の見直し余地。" }],
  decisions: ["現時点でCEOの判断を要する事項はありません。"],
  nextActions: ["指標を保存率へ切り替え、3施策へ集約する。"],
  appendix: [
    { label: "Generated by", value: "CMO" },
    { label: "Department", value: "Marketing" },
  ],
};

const taskCompletionContent: ReportContent = {
  subtitle: "F.R.I.D.A.Y. — Task Completion Report",
  period: formatDate(SEED_NOW),
  executiveSummary:
    "認証基盤の実装が完了しました。Supabase Auth を用いたCEOログイン、セッション保持、権限判定を実装し、E2Eテストは12件すべて通過しています。既知の劣化はありません。残るのは本番環境への反映のみで、これはCEO承認を必要とします。",
  keyMetrics: [
    { label: "E2E Tests", value: "12 / 12", positive: true },
    { label: "Regressions", value: "0", positive: true },
    { label: "Files Changed", value: "18" },
    { label: "Rollback Time", value: "≈40s" },
  ],
  departmentResults: deptResults(["engineering"]),
  projectResults: [
    { projectId: "friday", progress: 68, health: "on_track", note: "次は「Orchestrator 接続」。" },
  ],
  achievements: [
    { agentId: "backend_ai", text: "API と権限判定を実装。" },
    { agentId: "frontend_ai", text: "ログイン導線を実装。" },
    { agentId: "qa_ai", text: "E2Eで検証し12/12通過。" },
  ],
  findings: ["ロールバック手順を確立し、所要時間は約40秒。"],
  risks: [{ level: "low", text: "本番反映後は再認証が必要になります。" }],
  decisions: ["本番環境へのDeploy可否（Infrastructure AI）"],
  nextActions: ["承認後、午前中に本番反映とスモークテストを実施する。"],
  appendix: [
    { label: "Generated by", value: "Executive Assistant" },
    { label: "Task", value: "Dashboard authentication" },
  ],
};

const yesterdayContent: ReportContent = {
  ...dailyContent,
  subtitle: "全社 — Daily Executive Report",
  period: formatDate(ago(days(1))),
  executiveSummary:
    "本日は完了タスク48件。Re-Palette のSNS保存率が3日連続で改善し、開発は認証基盤の実装を80%まで到達させました。営業は提携候補の母数を確保し、次は接触の質が成果を決めます。",
  keyMetrics: [
    { label: "Completed Tasks", value: "48", delta: "+4", positive: true },
    { label: "AI Employees Active", value: "15" },
    { label: "Projects Updated", value: "7" },
    { label: "CEO Decisions Required", value: "3" },
  ],
};

export const SEED_REPORTS: Report[] = [
  {
    id: "rep-daily-0921",
    title: `Daily Executive Report — ${formatDate(SEED_NOW)}`,
    type: "daily",
    status: "PENDING_REVIEW",
    createdBy: "coo",
    sources: ["coo", "cmo", "cto", "cso", "research_director", "cfo"],
    createdAt: ago(minutes(12)),
    updatedAt: ago(minutes(12)),
    content: dailyContent,
    pdfUrl: pdf("rep-daily-0921"),
    requiresReview: true,
    priority: "high",
    version: 1,
    approvalId: "ap-report-daily",
  },
  {
    id: "rep-project-repalette",
    title: "Re-Palette — Project Report",
    type: "project",
    status: "PENDING_REVIEW",
    createdBy: "cmo",
    sources: ["cmo", "cso", "creative_director", "lead_ai", "designer_ai"],
    createdAt: ago(hours(2)),
    updatedAt: ago(hours(2)),
    projectId: "re_palette",
    content: projectContent,
    pdfUrl: pdf("rep-project-repalette"),
    requiresReview: true,
    priority: "medium",
    version: 1,
    approvalId: "ap-report-repalette",
  },
  {
    id: "rep-briefing-0921",
    title: `Morning Briefing — ${formatDate(SEED_NOW)}`,
    type: "briefing",
    status: "APPROVED",
    createdBy: "chief_of_staff",
    sources: ["chief_of_staff", "coo", "news_ai"],
    createdAt: MORNING_BRIEFING.generatedAt,
    updatedAt: ago(hours(8)),
    content: briefingContent,
    pdfUrl: pdf("rep-briefing-0921"),
    requiresReview: false,
    priority: "low",
    reviewedAt: ago(hours(8)),
    reviewedBy: "CEO",
    version: 1,
  },
  {
    id: "rep-weekly-w37",
    title: "Weekly Report — Week 37",
    type: "weekly",
    status: "APPROVED",
    createdBy: "coo",
    sources: week37.reports.map((r) => r.agentId),
    createdAt: ago(days(1) + hours(20)),
    updatedAt: ago(days(1) + hours(19)),
    content: weeklyContent,
    pdfUrl: pdf("rep-weekly-w37"),
    requiresReview: true,
    priority: "medium",
    reviewedAt: ago(days(1) + hours(18)),
    reviewedBy: "CEO",
    reviewComment: "決定事項4件すべて承認。NEWTONE を最優先で。",
    version: 1,
  },
  {
    id: "rep-research-beauty",
    title: "美容業界 市場規模 — Research Report",
    type: "research",
    status: "GENERATED",
    createdBy: "research_director",
    sources: ["research_director", "market_ai", "competitor_ai", "trend_ai"],
    createdAt: ago(minutes(45)),
    updatedAt: ago(minutes(45)),
    content: researchContent,
    pdfUrl: pdf("rep-research-beauty"),
    requiresReview: false,
    priority: "low",
    version: 1,
  },
  {
    id: "rep-dept-marketing",
    title: "Marketing — Department Report",
    type: "department",
    status: "APPROVED",
    createdBy: "cmo",
    sources: ["cmo", "content_ai", "seo_ai", "social_ai"],
    createdAt: ago(hours(5)),
    updatedAt: ago(hours(4)),
    departmentId: "marketing",
    content: departmentContent,
    pdfUrl: pdf("rep-dept-marketing"),
    requiresReview: true,
    priority: "low",
    reviewedAt: ago(hours(4)),
    reviewedBy: "CEO",
    version: 1,
  },
  {
    id: "rep-task-auth",
    title: "認証基盤の実装 — Task Completion Report",
    type: "task_completion",
    status: "DRAFT",
    createdBy: "chief_of_staff",
    sources: ["cto", "backend_ai", "frontend_ai", "qa_ai"],
    createdAt: ago(minutes(50)),
    updatedAt: ago(minutes(50)),
    projectId: "friday",
    content: taskCompletionContent,
    pdfUrl: pdf("rep-task-auth"),
    requiresReview: false,
    priority: "medium",
    version: 1,
  },
  {
    id: "rep-daily-0920",
    title: `Daily Executive Report — ${formatDate(ago(days(1)))}`,
    type: "daily",
    status: "ARCHIVED",
    createdBy: "coo",
    sources: ["coo", "cmo", "cto", "cso"],
    createdAt: ago(days(1) - hours(2)),
    updatedAt: ago(days(1) - hours(2)),
    content: yesterdayContent,
    pdfUrl: pdf("rep-daily-0920"),
    requiresReview: false,
    priority: "low",
    reviewedAt: ago(days(1) - hours(1)),
    reviewedBy: "CEO",
    version: 1,
  },
];

export const SEED_REPORTS_BY_ID: Record<string, Report> = Object.fromEntries(
  SEED_REPORTS.map((r) => [r.id, r]),
);
